@extends('layouts.print')
@section('title', 'Cashier closing report #'.$shift->id)
@section('content')
<div class="print-page">
    @include('print.partials.letterhead', ['title' => $shift->status === 'closed' ? 'Cashier Closing Report' : 'Cashier X Report (mid-shift)',
        'meta' => 'Shift #'.$shift->id.'<br>Printed '.now()->format('d M Y, H:i')])
    <div class="doc-grid">
        <div class="doc-box"><strong>Cashier</strong><br>{{ $shift->user->name }}<br><span class="doc-meta">Outlet: {{ $shift->outlet->name }}</span></div>
        <div class="doc-box"><strong>Shift period</strong><br>Opened {{ fmt_dt($shift->opened_at) }}<br>{{ $shift->closed_at ? 'Closed '.fmt_dt($shift->closed_at).' by '.($shift->closer?->name ?? '—') : 'Still open' }}</div>
    </div>
    @include('pos.partials.shift-reconciliation')
    @if ($shift->denominations)
        <h3 style="margin:18px 0 6px">Drawer count</h3>
        <table><thead><tr><th>Denomination</th><th class="num">Count</th><th class="num">Value</th></tr></thead><tbody>
            @foreach ($shift->denominations as $d => $n)<tr><td>LKR {{ number_format($d) }}</td><td class="num">{{ $n }}</td><td class="num">{{ money($d * $n, null, false) }}</td></tr>@endforeach
        </tbody></table>
    @endif
    <h3 style="margin:18px 0 6px">Cash movements</h3>
    <table><thead><tr><th>Time</th><th>Type</th><th>Reason / reference</th><th>User</th><th class="num">Amount</th></tr></thead><tbody>
        @foreach ($shift->movements as $m)<tr><td>{{ $m->created_at->format('d M H:i') }}</td><td>{{ $m->typeLabel() }}</td><td>{{ $m->reason }}{{ $m->reference ? ' · '.$m->reference : '' }}</td><td>{{ $m->user?->name }}</td><td class="num">{{ money($m->amount, null, false) }}</td></tr>@endforeach
    </tbody></table>
    @if ($shift->notes)<p class="doc-meta" style="margin-top:14px"><strong>Cashier notes:</strong> {{ $shift->notes }}</p>@endif
    @if ($shift->reviewed_at)<p class="doc-meta"><strong>Manager review:</strong> {{ ucfirst($shift->review_status) }} by {{ $shift->reviewer?->name }} on {{ fmt_dt($shift->reviewed_at) }}{{ $shift->review_notes ? ' — '.$shift->review_notes : '' }}</p>@endif
    <div class="doc-grid" style="margin-top:40px">
        <div>______________________________<br><span class="doc-meta">Cashier signature · {{ $shift->user->name }}</span></div>
        <div>______________________________<br><span class="doc-meta">Manager signature</span></div>
    </div>
    <div class="doc-foot">All amounts in LKR. Generated by Vaasal Villa HMS · {{ contact('location') }} · {{ contact('phone') }}</div>
</div>
@endsection
